// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Weather.Infra.Context;

#nullable disable

namespace Weather.Infra.Migrations
{
    [DbContext(typeof(DbPgContext))]
    partial class DbPgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Weather.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Weather.Domain.Entities.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CloudsAll")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FeelsLike")
                        .HasColumnType("double precision");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pressure")
                        .HasColumnType("integer");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeatherIcon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeatherId")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherMain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Weather");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Weather");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Weather.Domain.Entities.CurrentWeather", b =>
                {
                    b.HasBaseType("Weather.Domain.Entities.Weather");

                    b.HasDiscriminator().HasValue("CurrentWeather");
                });

            modelBuilder.Entity("Weather.Domain.Entities.DailyWeather", b =>
                {
                    b.HasBaseType("Weather.Domain.Entities.Weather");

                    b.Property<int?>("GroundLevel")
                        .HasColumnType("integer");

                    b.Property<double?>("Pop")
                        .HasColumnType("double precision");

                    b.Property<double>("RainVolume")
                        .HasColumnType("double precision");

                    b.Property<int?>("SeaLevel")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("DailyWeather");
                });

            modelBuilder.Entity("Weather.Domain.Entities.Weather", b =>
                {
                    b.HasOne("Weather.Domain.Entities.Location", "Location")
                        .WithMany("Weather")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Weather.Domain.Entities.Location", b =>
                {
                    b.Navigation("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
